Repository doctrine/DoctrineMongoDBBundle, pull requests merged in 2018-12, with the labels that each got.

#505 Better error message when missing document mapping
  Repository/ServiceDocumentRepository.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestUnmappedDocument.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestUnmappedDocumentRepository.php
  Tests/ServiceRepositoryTest.php
Labels: feature

#506 Fix more deprecations with Symfony 4.2
  Command/DoctrineODMCommand.php
  Command/InfoDoctrineODMCommand.php
  Command/LoadDataFixturesDoctrineODMCommand.php
  Resources/config/mongodb.xml
  Tests/Command/LoadDataFixturesDoctrineODMCommandTest.php
  Tests/ContainerTest.php
  Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
  Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
  Tests/ServiceRepositoryTest.php
Labels: task

#513 Remove last usage of ContainerAwareCommand
  Command/TailCursorDoctrineODMCommand.php
Labels: task

#514 Fix clearstatcache call arguments
  DoctrineMongoDBBundle.php
Labels: bug

#515 Prepare bundle for ODM Beta 1
  CacheWarmer/ProxyCacheWarmer.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Resources/config/mongodb.xml
  Tests/CacheWarmer/ProxyCacheWarmerTest.php
  Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
  Tests/DependencyInjection/ConfigurationTest.php
  Tests/TestCase.php
  composer.json
Labels: task

#517 Use Ubuntu 16.04
  .travis.yml
Labels: Enhancement
