Repository doctrine/DoctrineMongoDBBundle, pull requests merged in 2019-10, with the labels that each got.

#586 Fix deprecations when running against ODM 1.3
  .travis.yml
  Repository/ContainerRepositoryFactory.php
  Tests/DependencyInjection/Fixtures/config/yml/full.yml
  Tests/Mapping/Driver/YamlDriverTest.php
  Tests/TestCase.php
Labels: Enhancement

#589 Adding support for php 7.3 and 7.4 in branch 3.6
  .travis.yml
Labels: Enhancement

#590 Update supported versions in documentation
  .doctrine-project.json
Labels: Documentation

#588 Removing travis allow failure for php7.4
  .travis.yml
Labels: CI

#592 Authentication details
  Resources/doc/installation.rst
Labels: Documentation
