Repository doctrine/DoctrineMongoDBBundle, pull requests merged in 2019-06, with the labels that each got.

#529 First implementation of symfony fixture loader + group support #461
  Command/LoadDataFixturesDoctrineODMCommand.php
  DependencyInjection/Compiler/FixturesCompilerPass.php
  DependencyInjection/DoctrineMongoDBExtension.php
  DoctrineMongoDBBundle.php
  Fixture/Fixture.php
  Fixture/FixtureGroupInterface.php
  Fixture/ODMFixtureInterface.php
  Loader/SymfonyFixturesLoader.php
  Loader/SymfonyFixturesLoaderInterface.php
  Resources/config/mongodb.xml
  Tests/Command/LoadDataFixturesDoctrineODMCommandTest.php
  Tests/FixtureIntegrationTest.php
  Tests/Fixtures/FooBundle/DataFixtures/DependentOnRequiredConstructorArgsFixtures.php
  Tests/Fixtures/FooBundle/DataFixtures/OtherFixtures.php
  Tests/Fixtures/FooBundle/DataFixtures/RequiredConstructorArgsFixtures.php
  Tests/Fixtures/FooBundle/DataFixtures/WithDependenciesFixtures.php
  Tests/Fixtures/FooBundle/FooBundle.php
  Tests/ServiceRepositoryTest.php
  composer.json
Labels: Feature

#553 Replace getRootDir by getProjectDir
  Command/LoadDataFixturesDoctrineODMCommand.php
Labels: Enhancement

#556 Remove mocks to final class in tests
  Tests/CacheWarmer/HydratorCacheWarmerTest.php
  Tests/Repository/ContainerRepositoryFactoryTest.php
Labels: Task

#554 Drop file fixtures in favour of fixture services
  Command/LoadDataFixturesDoctrineODMCommand.php
Labels: Enhancement

#555 Remove legacy alias for document manager
  DependencyInjection/DoctrineMongoDBExtension.php
  Resources/doc/mongodb_library.rst
  Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
  Tests/FixtureIntegrationTest.php
  UPGRADE-4.0.md
Labels: Task

#559 Make sure doctrine/data-fixtures is really optional
  DependencyInjection/Compiler/FixturesCompilerPass.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Resources/config/mongodb.xml
Labels: bug
