Repository doctrine/DoctrineMongoDBBundle, pull requests merged in 2019-11, with the labels that each got.

#598 Cherry pick of #592 to 4.0
  Resources/doc/installation.rst
Labels: Documentation

#595 Document service repositories
  Resources/doc/first_steps.rst
Labels: Documentation

#602 Fix symfony 5 compatibility
  .travis.yml
  Command/InfoDoctrineODMCommand.php
  Command/LoadDataFixturesDoctrineODMCommand.php
  Command/TailCursorDoctrineODMCommand.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Tests/Form/Type/DocumentTypeTest.php
  Tests/Form/Type/TypeGuesserTest.php
  composer.json
Labels: Enhancement

#604 Fix wrong data collector signature
  .travis.yml
  DataCollector/CommandDataCollector.php
  DependencyInjection/Configuration.php
  README.markdown
  Tests/DataCollector/CommandDataCollectorTest.php
  composer.json
Labels: bug
