Repository doctrine/DoctrineMongoDBBundle, pull requests merged in 2019-02, with the labels that each got.

#530 Add PHP 7.4snapshot to build pipeline
  .travis.yml
Labels: Task

#531 Fix registration of the proxy autoloader
  DoctrineMongoDBBundle.php
Labels: bug

#534 Fix link to PHP7 usage instructions
  Resources/doc/index.rst
Labels: Documentation
