Repository doctrine/DoctrineMongoDBBundle, pull requests merged in 2020-03, with the labels that each got.

#618 Modernize documentation
  Resources/doc/config.rst
  Resources/doc/console.rst
  Resources/doc/cookbook/registration_form.rst
  Resources/doc/events.rst
  Resources/doc/first_steps.rst
  Resources/doc/form_validation.rst
  Resources/doc/index.rst
  Resources/doc/installation.rst
  Resources/doc/security_bundle.rst
Labels: Documentation

#617 Address deprecations from persistence library
  CacheWarmer/HydratorCacheWarmer.php
  CacheWarmer/PersistentCollectionCacheWarmer.php
  CacheWarmer/ProxyCacheWarmer.php
  DependencyInjection/Compiler/DoctrineMongoDBMappingsPass.php
  Form/ChoiceList/MongoDBQueryBuilderLoader.php
  Form/DoctrineMongoDBExtension.php
  Form/DoctrineMongoDBTypeGuesser.php
  Form/Type/DocumentType.php
  Repository/ContainerRepositoryFactory.php
  Repository/ServiceRepositoryTrait.php
  Resources/config/mongodb.xml
  Tests/CacheWarmer/PersistentCollectionCacheWarmerTest.php
  Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
  Tests/Fixtures/FooBundle/DataFixtures/DependentOnRequiredConstructorArgsFixtures.php
  Tests/Fixtures/FooBundle/DataFixtures/OtherFixtures.php
  Tests/Fixtures/FooBundle/DataFixtures/RequiredConstructorArgsFixtures.php
  Tests/Fixtures/FooBundle/DataFixtures/WithDependenciesFixtures.php
  Tests/Form/Type/DocumentTypeTest.php
  Tests/Form/Type/TypeGuesserTest.php
  Tests/Mapping/Driver/AbstractDriverTest.php
  composer.json
Labels: Enhancement

#623 Add marker interface for event subscriber autoconfiguration
  DependencyInjection/DoctrineMongoDBExtension.php
  EventSubscriber/EventSubscriberInterface.php
  Resources/doc/events.rst
Labels: Feature
