Repository doctrine/DoctrineMongoDBBundle, pull requests merged in 2021-09, with the labels that each got.

#693 Deprecate some unused `DoctrineODMCommand` methods
  Command/DoctrineODMCommand.php
  Command/InfoDoctrineODMCommand.php
  Tests/Command/CommandTestKernel.php
  Tests/Command/InfoDoctrineODMCommandTest.php
  Tests/Command/LoadDataFixturesDoctrineODMCommandTest.php
  Tests/Fixtures/CommandBundle/CommandBundle.php
  Tests/Fixtures/CommandBundle/DataFixtures/OtherFixtures.php
  Tests/Fixtures/CommandBundle/DataFixtures/UserFixtures.php
  Tests/Fixtures/CommandBundle/Document/User.php
  UPGRADE-4.4.md
  UPGRADE-5.0.md
  composer.json
Labels: Task

#699 Add TLS configuration options
  DependencyInjection/Configuration.php
  Resources/config/schema/mongodb-1.0.xsd
  Resources/doc/config.rst
  Tests/DependencyInjection/ConfigurationTest.php
  Tests/DependencyInjection/Fixtures/config/xml/full.xml
  Tests/DependencyInjection/Fixtures/config/yml/full.yml
Labels: Feature

#700 Update Documentation doctrine_mongodb.connections.default.options.connect is no longer a valid configuration option.
  Resources/doc/config.rst
Labels: Documentation
