Repository doctrine/DoctrineMongoDBBundle, pull requests merged in 2023-12, with the labels that each got.

#789 Remove deprecations using Symfony 6.4
  .github/workflows/continuous-integration.yml
  CacheWarmer/HydratorCacheWarmer.php
  CacheWarmer/PersistentCollectionCacheWarmer.php
  CacheWarmer/ProxyCacheWarmer.php
  Command/TailCursorDoctrineODMCommand.php
  Loader/SymfonyFixturesLoader.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestCustomClassRepoDocument.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestCustomServiceRepoDocument.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestCustomServiceRepoFile.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestDefaultRepoDocument.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestDefaultRepoFile.php
  Tests/DependencyInjection/Fixtures/TestKernel.php
  Tests/Fixtures/Cache/Collections.php
  Tests/Fixtures/CommandBundle/Document/User.php
  Tests/Fixtures/DataCollector/Category.php
  Tests/Fixtures/Form/Category.php
  Tests/Fixtures/Form/Document.php
  Tests/Fixtures/Form/Guesser.php
  Tests/Fixtures/Security/User.php
  Tests/Fixtures/Validator/Document.php
  Tests/ServiceRepositoryTest.php
  Tests/TestCase.php
  psalm-baseline.xml
Labels: Task

#793 Remove support of annotations
  Command/InfoDoctrineODMCommand.php
  DependencyInjection/Compiler/DoctrineMongoDBMappingsPass.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Resources/config/mongodb.xml
  Resources/doc/config.rst
  Resources/doc/cookbook/registration_form.rst
  Resources/doc/first_steps.rst
  Tests/Command/InfoDoctrineODMCommandTest.php
  Tests/ContainerTest.php
  Tests/DependencyInjection/AbstractMongoDBExtensionTestCase.php
  Tests/DependencyInjection/ConfigurationTest.php
  Tests/DependencyInjection/Fixtures/Bundles/AnnotationsBundle/AnnotationsBundle.php
  Tests/DependencyInjection/Fixtures/Bundles/AnnotationsBundle/Document/TestDocument.php
  Tests/DependencyInjection/Fixtures/config/xml/full.xml
  Tests/DependencyInjection/Fixtures/config/yml/full.yml
  Tests/ServiceRepositoryTest.php
  UPGRADE-5.0.md
  composer.json
Labels: Task

#794 Remove unused mapping services
  DependencyInjection/Compiler/DoctrineMongoDBMappingsPass.php
  Resources/config/mongodb.xml
Labels: Task

#797 Add return types required by extending Symfony classes
  CacheWarmer/HydratorCacheWarmer.php
  CacheWarmer/PersistentCollectionCacheWarmer.php
  CacheWarmer/ProxyCacheWarmer.php
  Command/ClearMetadataCacheDoctrineODMCommand.php
  Command/CreateSchemaDoctrineODMCommand.php
  Command/DoctrineODMCommand.php
  Command/DropSchemaDoctrineODMCommand.php
  Command/GenerateHydratorsDoctrineODMCommand.php
  Command/GenerateProxiesDoctrineODMCommand.php
  Command/InfoDoctrineODMCommand.php
  Command/LoadDataFixturesDoctrineODMCommand.php
  Command/QueryDoctrineODMCommand.php
  Command/ShardDoctrineODMCommand.php
  Command/UpdateSchemaDoctrineODMCommand.php
  DependencyInjection/Compiler/CreateHydratorDirectoryPass.php
  DependencyInjection/Compiler/CreateProxyDirectoryPass.php
  DependencyInjection/Compiler/FixturesCompilerPass.php
  DependencyInjection/Compiler/ServiceRepositoryCompilerPass.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Form/DoctrineMongoDBTypeGuesser.php
  Form/Type/DocumentType.php
  psalm-baseline.xml
Labels: Task

#798 Revert "Add $buildDir parameter to warmUp method"
  CacheWarmer/HydratorCacheWarmer.php
  CacheWarmer/PersistentCollectionCacheWarmer.php
  CacheWarmer/ProxyCacheWarmer.php
  phpunit.xml.dist
Labels: Task

#800 Mark command and compile pass classes, as internal
  Command/ClearMetadataCacheDoctrineODMCommand.php
  Command/CreateSchemaDoctrineODMCommand.php
  Command/DoctrineODMCommand.php
  Command/DropSchemaDoctrineODMCommand.php
  Command/GenerateHydratorsDoctrineODMCommand.php
  Command/GenerateProxiesDoctrineODMCommand.php
  Command/InfoDoctrineODMCommand.php
  Command/LoadDataFixturesDoctrineODMCommand.php
  Command/QueryDoctrineODMCommand.php
  Command/ShardDoctrineODMCommand.php
  Command/UpdateSchemaDoctrineODMCommand.php
  DataCollector/CommandDataCollector.php
  DependencyInjection/Compiler/CreateHydratorDirectoryPass.php
  DependencyInjection/Compiler/CreateProxyDirectoryPass.php
  DependencyInjection/Compiler/DoctrineMongoDBMappingsPass.php
  DependencyInjection/Compiler/FixturesCompilerPass.php
  DependencyInjection/Compiler/ServiceRepositoryCompilerPass.php
Labels: Task

#799 Remove `--service` option from `doctrine:mongodb:fixtures:load` command
  Command/LoadDataFixturesDoctrineODMCommand.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Loader/SymfonyFixturesLoaderInterface.php
  Resources/config/mongodb.xml
  UPGRADE-5.0.md
Labels: Task

#796 Mark all command and compiler pass classes as final
  Command/ClearMetadataCacheDoctrineODMCommand.php
  Command/CreateSchemaDoctrineODMCommand.php
  Command/DropSchemaDoctrineODMCommand.php
  Command/GenerateHydratorsDoctrineODMCommand.php
  Command/GenerateProxiesDoctrineODMCommand.php
  Command/InfoDoctrineODMCommand.php
  Command/LoadDataFixturesDoctrineODMCommand.php
  Command/QueryDoctrineODMCommand.php
  Command/ShardDoctrineODMCommand.php
  Command/UpdateSchemaDoctrineODMCommand.php
  DataCollector/CommandDataCollector.php
  DependencyInjection/Compiler/CreateHydratorDirectoryPass.php
  DependencyInjection/Compiler/CreateProxyDirectoryPass.php
  DependencyInjection/Compiler/DoctrineMongoDBMappingsPass.php
  UPGRADE-5.0.md
Labels: Task

#801 Deprecate container injection in fixture classes with `ContainerAwareInterface`
  Loader/SymfonyFixturesLoader.php
  UPGRADE-4.7.md
Labels: Task

#802 Remove container injection in fixture classes
  Loader/SymfonyFixturesLoader.php
  Resources/config/mongodb.xml
  UPGRADE-5.0.md
  psalm-baseline.xml
Labels: Task

#803 Remove CHANGELOG and old UPGRADE files
  CHANGELOG-4.0.md
  UPGRADE-3.5.md
  UPGRADE-4.0.md
  UPGRADE-4.4.md
  UPGRADE-4.6.md
  UPGRADE-4.7.md
Labels: Task

#808 Remove legacy config `fixture_loader`
  DependencyInjection/Configuration.php
  Tests/DependencyInjection/ConfigurationTest.php
  Tests/Form/Type/GuesserTestType.php
  Tests/Form/Type/TypeGuesserTest.php
  UPGRADE-5.0.md
Labels: Task

#805 Remove dependency to `jean85/pretty-package-versions`
  DependencyInjection/DoctrineMongoDBExtension.php
  composer.json
Labels: Task

#784 feat: Symfony 7 support
  .github/workflows/continuous-integration.yml
  DependencyInjection/Compiler/DoctrineMongoDBMappingsPass.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Form/DoctrineMongoDBExtension.php
  Form/DoctrineMongoDBTypeGuesser.php
  README.markdown
  Tests/Validator/Constraints/UniqueTest.php
  UPGRADE-5.0.md
  composer.json
Labels: Task

#812 Add native types
  APM/CommandLoggerRegistry.php
  Command/DoctrineODMCommand.php
  Command/LoadDataFixturesDoctrineODMCommand.php
  DependencyInjection/Compiler/DoctrineMongoDBMappingsPass.php
  DependencyInjection/DoctrineMongoDBExtension.php
  DoctrineMongoDBBundle.php
  Fixture/FixtureGroupInterface.php
  Form/ChoiceList/MongoDBQueryBuilderLoader.php
  Form/DoctrineMongoDBExtension.php
  Form/DoctrineMongoDBTypeGuesser.php
  Form/Type/DocumentType.php
  Loader/SymfonyFixturesLoader.php
  Loader/SymfonyFixturesLoaderInterface.php
  ManagerConfigurator.php
  ManagerRegistry.php
  Repository/ServiceRepositoryTrait.php
  Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
  Tests/Repository/ContainerRepositoryFactoryTest.php
  Validator/Constraints/Unique.php
  phpcs.xml.dist
Labels: Task

#815 Remove old code in DocumentType
  Form/Type/DocumentType.php
Labels: Task

#810 Migrate config to PHP
  DependencyInjection/DoctrineMongoDBExtension.php
  Resources/config/cache_warmer.php
  Resources/config/command.php
  Resources/config/form.php
  Resources/config/logger.php
  Resources/config/messenger.php
  Resources/config/messenger.xml
  Resources/config/mongodb.php
  Resources/config/mongodb.xml
  Resources/config/profiler.php
  Resources/config/validator.php
  Resources/config/value_resolver.php
  Resources/config/value_resolver.xml
  Tests/ContainerTest.php
  Tests/DependencyInjection/AbstractMongoDBExtensionTestCase.php
Labels: Task

#804 Drop support for Doctrine cache adapter for metadata
  DependencyInjection/Compiler/CacheCompatibilityPass.php
  DependencyInjection/DoctrineMongoDBExtension.php
  DoctrineMongoDBBundle.php
  Resources/doc/config.rst
  Tests/DependencyInjection/AbstractMongoDBExtensionTestCase.php
  Tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php
  Tests/DependencyInjection/ConfigurationTest.php
  Tests/DependencyInjection/Fixtures/config/xml/full.xml
  Tests/DependencyInjection/Fixtures/config/xml/mongodb_service_multiple_connections.xml
  Tests/DependencyInjection/Fixtures/config/xml/mongodb_service_simple_single_connection.xml
  Tests/DependencyInjection/Fixtures/config/yml/full.yml
  Tests/DependencyInjection/Fixtures/config/yml/mongodb_service_multiple_connections.yml
  Tests/DependencyInjection/Fixtures/config/yml/mongodb_service_simple_single_connection.yml
  Tests/DependencyInjection/Fixtures/config/yml/mongodb_service_single_connection.yml
  UPGRADE-5.0.md
Labels: Task

#811 Deprecate modifying class parameters
  DependencyInjection/Compiler/DeprecateChangedClassParametersPass.php
  DoctrineMongoDBBundle.php
  Tests/DependencyInjection/Compiler/DeprecateChangesClassParametersPassTest.php
  UPGRADE-4.7.md
Labels: Task

#822 Add priority to `#[AsDocumentListener]`
  Attribute/AsDocumentListener.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
  Tests/DependencyInjection/Fixtures/Bundles/DocumentListenerBundle/EventListener/TestAttributeListener.php
Labels: Enhancement

#825 Deprecate `AsDocumentListener` `$method` and `$lazy` (not working)
  Attribute/AsDocumentListener.php
  Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
  Tests/DependencyInjection/Fixtures/Bundles/DocumentListenerBundle/EventListener/TestAttributeListener.php
Labels: bug

#817 Deprecate `EventSubscriberInterface` in favor of `#[AsDocumentListener]`
  EventSubscriber/EventSubscriberInterface.php
  Resources/doc/events.rst
  UPGRADE-4.7.md
  UPGRADE-5.0.md
Labels: Documentation

#829 Remove version in internal annotation
  src/CacheWarmer/HydratorCacheWarmer.php
  src/CacheWarmer/PersistentCollectionCacheWarmer.php
  src/CacheWarmer/ProxyCacheWarmer.php
  src/Command/ClearMetadataCacheDoctrineODMCommand.php
  src/Command/CreateSchemaDoctrineODMCommand.php
  src/Command/DoctrineODMCommand.php
  src/Command/DropSchemaDoctrineODMCommand.php
  src/Command/GenerateHydratorsDoctrineODMCommand.php
  src/Command/GenerateProxiesDoctrineODMCommand.php
  src/Command/InfoDoctrineODMCommand.php
  src/Command/LoadDataFixturesDoctrineODMCommand.php
  src/Command/QueryDoctrineODMCommand.php
  src/Command/ShardDoctrineODMCommand.php
  src/Command/UpdateSchemaDoctrineODMCommand.php
  src/DataCollector/CommandDataCollector.php
  src/DependencyInjection/Compiler/CreateProxyDirectoryPass.php
  src/DependencyInjection/Compiler/DoctrineMongoDBMappingsPass.php
  src/DependencyInjection/Compiler/FixturesCompilerPass.php
  src/DependencyInjection/Compiler/ServiceRepositoryCompilerPass.php
Labels: Task

#831 Fix partial service removed when fixtures package is not installed
  src/DependencyInjection/DoctrineMongoDBExtension.php
Labels: bug
