Repository doctrine/DoctrineMongoDBBundle, pull requests merged in 2023-03, with the labels that each got.

#754 Wire the EntityArgumentResolver
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Resources/config/mongodb.xml
  Tests/DependencyInjection/ConfigurationTest.php
  Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
Labels: Feature

#769 Use PHP 7.4 syntax
  CacheWarmer/ProxyCacheWarmer.php
  Command/InfoDoctrineODMCommand.php
  DataCollector/CommandDataCollector.php
  DependencyInjection/Compiler/ServiceRepositoryCompilerPass.php
  DependencyInjection/Configuration.php
  Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
  Tests/FixtureIntegrationTest.php
  Tests/Repository/ContainerRepositoryFactoryTest.php
Labels: Task

#768 Use PHP 7.4 for phpcs
  .github/workflows/continuous-integration.yml
  DataCollector/CommandDataCollector.php
  DependencyInjection/Compiler/CacheCompatibilityPass.php
  DependencyInjection/Compiler/CreateHydratorDirectoryPass.php
  DependencyInjection/Compiler/CreateProxyDirectoryPass.php
  DependencyInjection/Compiler/DoctrineMongoDBMappingsPass.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Form/DoctrineMongoDBTypeGuesser.php
  Form/Type/DocumentType.php
  Loader/SymfonyFixturesLoader.php
  Repository/ServiceRepositoryTrait.php
  Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
  Tests/DependencyInjection/Compiler/CacheCompatibilityPassTest.php
  Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
  Tests/DependencyInjection/Fixtures/Bundles/AnnotationsBundle/Document/Test.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestCustomClassRepoDocument.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestCustomServiceRepoDocument.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestDefaultRepoDocument.php
  Tests/FixtureIntegrationTest.php
  Tests/Fixtures/CommandBundle/Document/User.php
  Tests/Form/Type/DocumentTypeTest.php
  Tests/Mapping/Driver/AbstractDriverTest.php
  Tests/Repository/ContainerRepositoryFactoryTest.php
  Tests/ServiceRepositoryTest.php
  phpcs.xml.dist
Labels: Task

#772 Fix CS
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestCustomClassRepoDocument.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestCustomServiceRepoDocument.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestCustomServiceRepoFile.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestDefaultRepoDocument.php
  Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestDefaultRepoFile.php
  Tests/Fixtures/CommandBundle/Document/User.php
Labels: Task

#762 CI: Update GH actions
  .github/workflows/composer-lint.yml
  .github/workflows/continuous-integration.yml
  .github/workflows/lint.yaml
  .github/workflows/release-on-milestone-closed.yml
  .github/workflows/static-analysis.yml
Labels: CI

#771 Drop support of unmaintained versions of Symfony
  .github/workflows/continuous-integration.yml
  CacheWarmer/HydratorCacheWarmer.php
  CacheWarmer/PersistentCollectionCacheWarmer.php
  CacheWarmer/ProxyCacheWarmer.php
  DependencyInjection/Configuration.php
  DependencyInjection/DoctrineMongoDBExtension.php
  Form/ChoiceList/MongoDBQueryBuilderLoader.php
  Form/DoctrineMongoDBTypeGuesser.php
  Form/Type/DocumentType.php
  Loader/SymfonyFixturesLoader.php
  ManagerConfigurator.php
  README.markdown
  Resources/doc/messenger.rst
  Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
  Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
  Tests/FixtureIntegrationTest.php
  Tests/Form/Type/DocumentTypeTest.php
  Tests/Form/Type/TypeGuesserTest.php
  Tests/Mapping/Driver/AbstractDriverTest.php
  Tests/Mapping/Driver/XmlDriverTest.php
  composer.json
Labels: Task
