Repository doctrine/DoctrineMongoDBBundle, pull requests merged in 2025-01, with the labels that each got.

#853 [Feature] Support custom not found message based on Doctrine Bridge MapEntity
  src/Attribute/MapDocument.php
Labels: bug

#876 Exclude classes with `#[Document]` attribute from container
  src/DependencyInjection/DoctrineMongoDBExtension.php
Labels: Feature

#877 Use LazyGhostObject for proxy objects
  config/mongodb.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/DoctrineMongoDBExtension.php
  tests/DependencyInjection/ConfigurationTest.php
Labels: Enhancement

#878 Ignore issue for `method_exists` always `true` reported by phpstan
  phpstan-baseline.neon
Labels: bug
